# Secrets Configuration For GymPro App
# This file is actively parsed as a fallback if keys are missing from BuildConfig

# m5ssas m5ss 7b3y ll-mohamat el-nasiya w el-chat
GEMINI_API_KEY=

# m5ssas m5ss 7b3y ll-modeb el-soti w native audio-to-audio
VOICE_COACH_API_KEY=
